<?php

namespace AppBundle\Repository;

/**
 * AttemptsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttemptsRepository extends \Doctrine\ORM\EntityRepository
{
}