<?php

namespace AppBundle\Repository;

/**
 * DlcTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DlcTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
