<?php

namespace AppBundle\Repository;

/**
 * EnvironmentOde
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvironmentOdeRepository extends \Doctrine\ORM\EntityRepository
{

}