<?php

namespace AppBundle\Repository;

/**
 * ExperimentEvaluation
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperimentEvaluationRepository extends \Doctrine\ORM\EntityRepository
{

}