<?php

namespace AppBundle\Repository;

/**
 * JointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JointsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getLeftJoints()
    {
        $qb = $this->createQueryBuilder('lg');

        $qb->select('lg');

        $qb
            ->andWhere($qb->expr()->like('lg.name', ':name'))
            ->setParameter('name', '%' . 'L.' . '%')
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * @return array
     */
    public function getRightJoints()
    {
        $qb = $this->createQueryBuilder('rg');

        $qb->select('rg');

        $qb
            ->andWhere($qb->expr()->like('rg.name', ':name'))
            ->setParameter('name', '%' . 'R.' . '%')
        ;

        return $qb->getQuery()->getResult();
    }
}