<?php

namespace AppBundle\Repository;

use AppBundle\Traits\RepositoryPaginatorTrait;

/**
 * OperatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatorRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryPaginatorTrait;

    /**
     * @param int $currentPage
     * @param int $perPage
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function getAvailableOperators($currentPage = 1, $perPage = 20)
    {
        $qb = $this->createQueryBuilder('op');

        $qb->select('op');

        $paginator = $this->paginate($qb, $currentPage, $perPage);
        return $paginator;
    }
}
