#services:
#    app.admin.project:
#        class: AppBundle\Admin\ProjectAdmin
#        arguments: [~, AppBundle\Entity\Project, AppBundle:ProjectAdmin]
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: admin, label: Project }

services:
    app.admin.indicators:
      class: AppBundle\Admin\MedicalIndicatorAdmin
      arguments: [~, AppBundle\Entity\Indicator, SonataAdminBundle:CRUD]
      tags:
      - { name: sonata.admin, manager_type: orm, group: Experiments, label: Medical indicators }