<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Symfony\Component\Security\Core\Role\Role;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function isPurchasingLeader()
    {
        foreach ($this->getGroups() as $group) {
            if ($group->hasRole('ROLE_PURCHASING_LEADER')) {
                return true;
            }
        }

        return false;
    }

    public function canViewModels()
    {
        foreach ($this->getGroups() as $group) {
            if ($group->hasRole('ROLE_CAN_VIEW_MODELS')) {
                return true;
            }
        }

        return false;
    }

    public function canViewExperiments()
    {
        foreach ($this->getGroups() as $group) {
            if ($group->hasRole('ROLE_CAN_VIEW_EXPERIMENTS')) {
                return true;
            }
        }

        return false;
    }
}
